SET NAMES UTF8;
DROP DATABASE IF EXISTS fs;
CREATE DATABASE fs CHARSET=UTF8;
USE fs;
CREATE TABLE fs_user(
	uid INT PRIMARY KEY AUTO_INCREMENT,
	phone CHAR(11) NOT NULL,
	password VARCHAR(16) NOT NULL,
	uname VARCHAR(32),
	gender BOOL DEFAULT 0,
	email VARCHAR(16),
	birthday VARCHAR(10),
	reg_time VARCHAR(16) NOT NULL
);
INSERT INTO fs_user VALUES('1','13513636547','张总','0','zz@126.com','1974-4-4');